// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "Books N Cup",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "/hero.jpg",
  "aboutQuote": "We opened Books N Cup to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "07392 072241",
  "email": "bookandcupcafe@gmail.com",
  "address": [
    "23 Home Street",
    "Edinburgh."
  ]
};
